/** Bundle the browser entry into the DSH lazy-factory registration protocol. */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
const result = await build({
  absWorkingDir: fileURLToPath(new URL('..', import.meta.url)),
  entryPoints: ['src/client.js'], bundle: true, write: false,
  tsconfigRaw: { compilerOptions: { strict: true } },
  format: 'cjs', platform: 'browser', target: 'es2022', legalComments: 'none',
  loader: { '.css': 'text' },
  external: ['react', '@deepseek-ai/dsh-client-ui-primitives'],
});
const code = '/* Generated by npm run build. Edit src/client.js and src/catalog.js. */\n'
  + 'window.__ModuleLoader__.load({id:' + JSON.stringify(pkg.name) + ',factory(require){\n'
  + 'const module={exports:{}};const exports=module.exports;\n'
  + result.outputFiles[0].text + '\nreturn module.exports;\n}});\n';
await writeFile(new URL('../client.js', import.meta.url), code);
